version: '3.3'

services:
  mongodb:
    # This image automatically creates a replica set required for transactions
    build: ./image
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
      MONGO_REPLICA_HOST: ${MONGO_REPLICA_HOST}
      MONGO_REPLICA_PORT: ${MONGO_REPLICA_PORT}
    volumes:
      - ./data:/data/db